apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: carrier-mutator
webhooks:
  - admissionReviewVersions:
      - v
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvekNDQWVlZ0F3SUJBZ0lKQUx5YlU2UVZIeFN5TUEwR0NTcUdTSWIzRFFFQkN3VUFNQlV4RXpBUkJnTlYKQkFNTUNuZGxZbWh2YjJ0ZlkyRXdJQmNOTWpFd01qSTJNRFkwTWpRMVdoZ1BNakk1TkRFeU1USXdOalF5TkRWYQpNQlV4RXpBUkJnTlZCQU1NQ25kbFltaHZiMnRmWTJFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFEQVdRbG5QMWhIMGd0Qmg4dGtvSE1jblV2SFVqWFRoRWVxRVd5c290N2RUM3YrZVQ0dmhVRmEKdldRK1pBWm9PSDFYeTBnZk03dkQvbzNDbkZMcXUxRmxWem5kYVdwaStnUndtWDJnNUs3bzYxWFFEY1lkYk5qYwpnT3FqSGxWdzBLaTdsOWtaQnExbEo2ZUEyd29XQWFaMG9ROTFyY0lhbUJSRnE3di8xNEFNQnFtWkkwMWN6V2NjCjAzbWxsd2JCMnh6dktCbkNlUHNXVmZpdTZqK0MrbWp1K3NCRjQxN1BqZ1lDekVEbUw4Y1AwRHFZN3Y2NTFZNjcKWjhkNTBjbTJKdmthSWZRTEpiSnQva211ZjMxVXZOWkhaNE1NUC96dUd6UXlmWWtDaXFkYk5mWVZUbnphUWRjUgoxcStUaTRKUkpuUTNFcVJBRnRHSzlsUHVCMkh5K3RWREFnTUJBQUdqVURCT01CMEdBMVVkRGdRV0JCVG9mblA0ClplQjlyM09xWUdTMnRjNWlvZjM4T3pBZkJnTlZIU01FR0RBV2dCVG9mblA0WmVCOXIzT3FZR1MydGM1aW9mMzgKT3pBTUJnTlZIUk1FQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNyT21EVVlDWDczbFY3YXhTbQprZ2xaeHlNWGh1MXIzekhvMk4zK1JyR1dwWWp0UHZBVWlWN2RQNUdyQTdzTWQyRmp3SEtsb2lSVUVRSzYrazNWCjluc1FtY1NZdmxaazhtRFdBdWxuaHI2aDdhS0tRTmlXZEp4Tzd6ODlvcTYrczVUZDdCNmRuYkdYelNMRE53WFoKQmVKcnJqM2hBVEVwS1BxeXhRQkhrcWhHb3hxNkR2Z08xRUVJMTlvNUpGU0J3K3pYYTRsRmpVcSttbzJ2Uk1vYwpweUNydjRqZHEyNDMwcHNjSDRCb1RPcXBQek9tWUNZTExvb1dmTkdWSWRUS1hSc1RIRXlFNjUzbXNSeHdVVGhtClBCenYxTDdlTlpsaHRybjNTUUVNTWxUUkdrdWgxMzFJWXNOaTRBemJLRVIybHhCdGtzOTJFcGswZ2ZNa0llUU4KWTVRVAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        namespace: kube-system
        name: carrier-webhook-service
        path: /mutate
    failurePolicy: Ignore
    name: carrier-webhook.ocgi.dev
    namespaceSelector:
      matchExpressions:
        - key: ns
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - "carrier.ocgi.dev"
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - '*'
        scope: '*'
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - 'pods'
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10